language: cpp
before_script:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update
- sudo apt-get install g++-7 -y
- sudo apt-get install doxygen -y
- sudo apt-get install graphviz -y
- cd /usr/bin
- sudo rm g++
- sudo ln g++-7 g++
- cd "${TRAVIS_BUILD_DIR}"
script:
- cmake .
- cmake --build .
- doxygen
deploy:
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: html
  on:
    branch: master